### ISSUE TITLE
Errors logged  by default

### ISSUE THREAD

**Issue by kpcyrd** [rust-cli/env_logger#118]
Hello!

This is more of a question, but it seems the default loglevel for env_logger includes `error`. While I would like to allow setting a log level with `RUST_LOG=`, I would also like to fully disable logging if that environment variable isn't set because it's interfering with the process indicator. I have my own error handling and one of my dependencies is using `error!` in some cases which messes with the terminal.

I was wondering: What's the most elegant way to have an env_logger that defaults to "fully silent"? :)

**Comment by KodrAus** [comment]
Hi @kpcyrd :wave:

Are you saying one of your library dependencies is using `env_logger` to write its logs to the terminal? Or that you're using `env_logger`, which is just capturing its `error!` calls?

If it's the latter, I'm on mobile right now, but you should be able to create a logger from an env that defaults to off instead of error:

```rust
env_logger::init_from_env(Env::default()
    .default_filter_or("off"));
```

If it's the former then we should try fix that up :)
